summary: XML-based font configuration library
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-10.15-x86_64/releases/download/2024.06.02/libfontconfig-2.15.0-macos-10.15-x86_64.tar.xz
bin-sha: bb2b78662d42f9061f5bbd93ee356dca270786d343a5f4e1a9fd63772645e3cc
